### ISSUE TITLE
Full / incremental backup creation time

### ISSUE THREAD

**Issue by cmonty14** [omegazeng/run-mariabackup#3]
Hello,
can you please document when a full / incremental backup is created?
I understand that the script is triggered by a cron job, but I don't understand what conditions define if there's a full or incremental backup.

THX

**Comment by omegazeng** [comment]
https://github.com/omegazeng/run-mariabackup/blob/master/run-mariabackup.sh#L16

**Comment by cmonty14** [comment]
Ah... this means any backup created in between FULLBACKUPCYCLE is an incremental backup?
That is clever!
